# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 479582e8c432f667d63a92c460d396b8108514c6f2a2aceab318573ea18acb7e131d73a08b0ebb6767f2f3a873a84f8a8cafd2a460c2e19f77ef73fa0342d483

test:
  secret_key_base: 572d9b243c29f77813c5d420954512549d9fc90c04c15e29008c08c69ecd06fbd047b57347bd400476850d4cfec6082a2090013ff7d70cfd8b488148a9b8ab5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
